### ISSUE TITLE
[Request] Personal domain filter option for crowd-bypass

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#238]
There are specific domains where crowd-bypass doesn't work well. So, instead of using Universal-Bypass there I'd like to use another bypasser. But popping up of crowd-bypass suggestion doesn't let that happen.

Example Link: https://bc.vc/pVIcypk#

**Comment by timmyrs** [comment]
If you have a better way of bypassing bc.vc, let me know how.

**Comment by Cyberavater** [comment]
You can add if you want along with the crowd bypass
https://github.com/adsbypasser/adsbypasser/blob/938cb94aa48cb234b0cf325d7b76459759848536/src/sites/link/bc.vc.js
But there are cases where crowd bypass keeps looping because of domain's complexity so, this feature might come handy at some case anyway.

**Comment by timmyrs** [comment]
If I understand that code correctly, it waits 5 seconds, so I don't see the point of it. And what exactly is Crowd Bypass doing wrong here?

**Comment by version365** [comment]
The problem with bc.vc is that.. normally (i.e. without any extension) a bc.vc link gives the correct target link only the first time, but if you refresh that page or hit the back button, it goes to `track.bcvc.mobi` which is an ad site.
So, sometimes this `track.bcvc.mobi` is captured as target link by crowd bypass rather than the correct link.

If you could only blacklist the `track.bcvc.mobi` site from crowd-bypass database, then this problem would probably be solved.

**Comment by timmyrs** [comment]
Alright, I've blacklisted track.bcvc.mobi in the backend, so I suppose this issue can now be closed.

**Comment by Cyberavater** [comment]
Yes, that somehow fixes the problem.

**Comment by version365** [comment]
This problem is happening again..
`https://bc.vc/USorQn9` leads to `http://track.bcvc.mobi/earn.php?zone=6&uid=964&code=jx75&ref=https%3A%2F%2Fbc.vc%2FUSorQn9` when UniBy is enabled.

**Comment by timmyrs** [comment]
Sorry, I wrote some bad code in the backend. Should be fixed now for real tho.
