### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [timmyRS/Universal-Bypass#502]
Follow up to https://addons.mozilla.org/addon/universal-bypass/reviews/1405465/

https://addons.mozilla.org/addon/universal-bypass/versions/10.43/updateinfo/ is empty, and so on; no note for any of the 25 versions at https://addons.mozilla.org/addon/universal-bypass/versions/

Thanks

**Comment by timmyRS** [comment]
The only place I'm keeping a changelog right now is https://universal-bypass.org/changelog
All the latest versions on AMO get that link as the release notes, but I'm no longer creating a seperate changelog on AMO because it's a hassle for me to create and not very practical for users who are actually interested in the changes over more than 1 version.

**Comment by grahamperrin** [comment]
> All the latest versions on AMO get that link as the release notes, 

That's fine :-) looking forward to seeing the link when the next release is made.

**Comment by grahamperrin** [comment]
Six weeks later, wondering why I could not see the link to release notes at AMO, eventually I realised: 

- https://addons.mozilla.org/en-GB/firefox/addon/universal-bypass/versions/11.5/updateinfo/ English = empty
- https://addons.mozilla.org/en-US/firefox/addon/universal-bypass/versions/11.5/updateinfo/ English = non-empty. 

I'l make an enhancement request to Mozilla.

**Comment by timmyRS** [comment]
I didn't even know you could translate the changelog. I've deleted the en-gb locale, so that should've fixed it.
